# Generated by Django 3.2.6 on 2021-09-03 12:36

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='article',
            field=django_quill.fields.QuillField(),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
